DROP TABLE IF EXISTS blog_sections CASCADE;
DROP TABLE IF EXISTS blogs CASCADE;

CREATE TABLE blogs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  author_id VARCHAR(255) NOT NULL,
  author_name VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL DEFAULT 'Untitled Blog',
  cover_image_url VARCHAR(1024),
  published BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE blog_sections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  blog_id UUID NOT NULL REFERENCES blogs(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL, -- 'title', 'image', 'code', 'paragraph'
  content TEXT NOT NULL,
  sub_title VARCHAR(255),
  order_index INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
